### PR TITLE
Fix TypeError when encountering XML with missing testsuite or testcase elements

### LINKED ISSUE #8: Cannot read property 'skipped' of undefined
Hi,

During the build of my project I have this error : `##[error]Cannot read property 'skipped' of undefined`

Do you any clue on the problem ?

Thanks.

### PR DESCRIPTION
**Pull request by djcsdy**
Fixes #8.

### CODE REVIEW

**Comment by djcsdy** [comment]
Urgh... you can safely ignore the failing build.

The build is failing because I added some test cases to trigger this bug, in order to verify that my changes fix this bug. But since the `build.yml` references `scacap/action-surefire-report@master`, my test cases are triggering this bug in the old code. Once this change is merged into master the build will pass.

**Comment by jmisur** [comment]
Hi @djcsdy , is this still broken on master?
BTW you can just change the branch to verify that it reports correctly, then change back to master.
Also, how did you manage to get empty report? How does Java test look like?

**Comment by djcsdy** [comment]
Just looking at the code on master, I would expect it to be even worse. Because you've written this:

https://github.com/ScaCap/action-surefire-report/blob/016072f6281d1cd3e570d342c03e9277558c5fd2/utils.js#L39-L43

Which, if `report.testsuite` is an array, skips the `isArray` check and gives you an array wrapped in an array

https://github.com/ScaCap/action-surefire-report/blob/016072f6281d1cd3e570d342c03e9277558c5fd2/utils.js#L40

and if `report.testsuite` is `undefined`, gives you the array `[undefined]`, which is the same as was happening before in that case.

https://github.com/ScaCap/action-surefire-report/blob/016072f6281d1cd3e570d342c03e9277558c5fd2/utils.js#L43

**Comment by djcsdy** [comment]
Sorry I stand corrected, I misread the above code.

It does work on master now.

I have no idea how to write test cases that produce an empty report. Probably there is no way to do that and what actually happened is that some tests produced a file with `testcase` wrapped in `testsuite`, as handled by your code. Our build produces thousands of XML reports and I wasn't able to find the specific one that caused the problem.

**Comment by jmisur** [comment]
Great to hear that it works.

**Pull request closed without merging**
