### PR TITLE
Improve junit file handling

### PR DESCRIPTION
**Pull request by jinhong-**
This PR aims to improve compatibility of reading junit xml files. Current implementation assumes that the root element will be "testsuite", which may not be true for all cases. Having "testsuites" as the root element is also considered valid junit xml file

### CODE REVIEW

**Comment by jmisur** [comment]
Hi @jinhong- thanks for submission! Would you be so kind and enhance the test maven project in `test` folder with such test which produces `testsuites` in root element, so that we have a running example. Also add test for this file into `action.test.js` to make sure it works.

**Comment by j-blue-arz** [comment]
It is impossible to write a test which produces a `testsuites` root element, because it is not supported by the maven surefire plugin, see the official [schema](http://maven.apache.org/surefire/maven-surefire-plugin/xsd/surefire-test-report-3.0.xsd).

Many other test runners for other languages (e.g. pytests, googletests) produce .xml files which conform the [JUnit XML schema](https://llg.cubic.org/docs/junit/). The `testsuites` root element is part of this schema. 
I do not know if these two are compatible, so it is unclear if the pull request can be successful. But I'd really like to see it, because test reporting is currently missing in github actions.

**Comment by jmisur** [comment]
Thanks for contribution. I'll try to use this in another branch and also include some real life tests to make sure it works, probably using pytest.

**Comment by jmisur** [comment]
Thanks for contribution, I pulled this code in #7

**Pull request closed without merging**
