### PR TITLE
[BXMSPROD-1311] be able to skip check run

### PR DESCRIPTION
**Pull request by Ginxo**
https://issues.redhat.com/browse/BXMSPROD-1311

We would like to skip check run creation for a pull request event (otherwise it will fail)

You can check an execution example here https://github.com/kiegroup/droolsjbpm-build-bootstrap/pull/1639/checks?check_run_id=2544538267

### CODE REVIEW

**Comment by jmisur** [comment]
Hi @Ginxo,
I don't see the issue (no permission?)
Anyway creating check run and reporting there is the primary purpose of this plugin. If you need skip it entirely on some condition could you use [gh action workflow if statement](https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif)?

**Comment by danielezonca** [comment]
Hi @jmisur 
The error we got is this
https://github.com/kiegroup/kogito-runtimes/pull/1292/checks?check_run_id=2545611473
`Error: Resource not accessible by integration`
And it seems related to GitHub permissions (we use `pull_request` event) https://github.com/actions/first-interaction/issues/10#issuecomment-812128937

Just to give you a bit more of context, we have a multirepo project and we are using Jenkins for CI configured to execute all repos even in case of test failures (using `-Dmaven.test.failure.ignore=true`) and then after the build we parse surefire report and decide if the build failed or not.
Now we are implementing CI with GH action and we need to replicate the same behaviour: using `action-surefire-report` we can get the expected behaviour for free using the `fail_on_test_failures` option.

The only remaining problem we have (and this is the reason of this PR) is that using `pull_request` event (we cannot change it to `pull_request_target` because we use PR from fork also to test CI changes) the `action-surefire-report` fails to publish the report after the execution making all builds fail.
With this additional config we want to preserve the possibility to use this action even without the report published. This is the result
https://github.com/kiegroup/drools-wb/runs/2545873814
And the message in the log with the list of failed test is enough for our needs.

**Comment by jmisur** [comment]
I see. The forked PR bug is super annoying. I'll pick this soon, thanks.

**Comment by jmisur** [comment]
Thanks for the contribution. I included it in my PR.

**Pull request closed without merging**
