### PR TITLE
Add automatic retries when talking to Github API

### PR DESCRIPTION
**Pull request by nineinchnick**
Adding annotations should not make the whole pipeline fail if there are transient networking issues.

Use the plugin recommended in docs: https://octokit.github.io/rest.js/v18#automatic-retries

### CODE REVIEW

**Comment by nineinchnick** [comment]
It'll cause conflicts with #81 but I'll resolve them whenever one of the PRs gets merged.

**Comment by ghaiszaher** [comment]
@nineinchnick thank you for your contribution. Could you resolve the conflicts so we can take a look?

> Adding annotations should not make the whole pipeline fail if there are transient networking issues.

I totally agree with your argument. But is this a real issue you're facing?

**Comment by nineinchnick** [comment]
@ghaiszaher rebased. Yes, we were hitting networking issues in our repos. We've been using a fork of this action since then, with the retry plugin enabled.

**Review by crypticmind — APPROVED** [review]

**Review by ghaiszaher — DISMISSED** [review]

**Review by renatoabreu11 — DISMISSED** [review]

**Comment by renatoabreu11** [comment]
@nineinchnick Please merge with the master branch again.

**Comment by nineinchnick** [comment]
@renatoabreu11 done!

**Review by renatoabreu11 — APPROVED** [review]

**Review by ghaiszaher — APPROVED** [review]

**Review by crypticmind — APPROVED** [review]

**Pull request merged**
